### ISSUE TITLE
Error while scrapping specific comic

### ISSUE THREAD

**Issue by pweasel** [cbanack/comic-vine-scraper#412]
Only when this one comic tries to get scrapped it bring an error, logfile appended:

--------------------------------------------------------------------------------
CV Scraper Version:  1.0.87
Running As:          ComicRack Plugin (CR version 0.9.176)
Cache Directory:     C:\Users\pweasel\AppData\Roaming\Comic Vine Scraper\localCache
Settings File:       C:\Users\pweasel\AppData\Roaming\Comic Vine Scraper\settings.dat
--------------------------------------------------------------------------------

--------------------------------------------------------------------
[X] Series          [X] Volume          [X] Number          
[X] Title           [X] Published       [X] Released        
[X] Crossovers      [X] Publisher       [X] Imprint         
[X] Writer          [X] Penciller       [X] Inker           
[X] Colorist        [X] Letterer        [X] Cover Art       
[X] Editor          [X] Summary         [X] Characters      
[X] Teams           [X] Locations       [X] Webpage         
-------------------------------------------------------------------
[X] Overwrite Existing        [X] Ignore Blanks             
[X] Convert Imprints          [X] Autochoose Series         
[X] Download Thumbs           [X] Preserve Thumbs           
[ ] Confirm Issues            [X] Rescraping: Notes         
[X] Fast Rescrape             [X] Rescraping: Tags          
[X] Summary Dialog            
-------------------------------------------------------------------
Ignore all series published by 'abril'
Ignore all series published by 'marvel italia'
Ignore all series published by 'panini'
Ignore all series published by 'planeta deagostini'
Ignore all series published by 'marvel uk'
Ignore all series published by 'semic as'
Ignore all series published by 'panini comics'
-------------------------------------------------------------------

======> scraping next comic book: 'Sin of Omniscience Vol.2013 #00 (02-2013).cbr'
trying to match this book automatically...
------------------- PYTHON ERROR ------------------------
Caught ValueError: bad parameters
Traceback (most recent call last):
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 143, in scrape
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 257, in _ScrapeEngine__scrape
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 426, in _ScrapeEngine__scrape_book
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\automatcher.py", line 44, in find_series_ref
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\db.py", line 194, in query_issue_ref
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvdb.py", line 370, in query_issue_ref
  File "C:\Users\pweasel\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvconnection.py", line 118, in _query_issue_id_dom

wrote debug logfile: cvs-debug-log-2015-06-17.txt

**Comment by pweasel** [comment]
I'm an idiot

**Comment by cbanack** [comment]
Bug was fixed in 1.0.88, as I think you just noticed. :)
